### ISSUE TITLE
Support applying noflip to one consecutive section of the stylesheet

### ISSUE THREAD

**Issue by tomyam1** [cssjanus/cssjanus#28]
Is it possible to no-flip a set of selectors, for example:

``` css
/* rule1 and rule2 will be preserved
/* @noflipStart */
.rule1 {...}
.rule2 {...}
/* @noflipEnd */
```

My use case is that I put all CSS in one file and than pass it through cssjanus to get an RTL version of it. Some libraries already handle RTL themselves so I don't want to process them. Something like `noflipStart` and `noflipEnd` will allow to do that.

**Comment by Krinkle** [comment]
@tomyam1 I'm sorry, but I don't believe adding this feature is in the best interest of keeping the library simple and easy to maintain in the future. Adding start/end annotations would make parsing more complicated in the future and requires maintaining state in a way I'd like to avoid.

For more fine-grained control, I recommend flipping individual components instead and concatenating them later on. This also allows for better use of caching and reduced computation time when re-running the workflow after a change was made one or more components.
