### ISSUE TITLE
Add demo html page and stylesheet

### ISSUE THREAD

**Issue by Krinkle** [cssjanus/cssjanus#37]
This would help show off how CSSJanus behaves and makes changes easier to verify visually.

Once in the repo, we can publish it on https://cssjanus.github.io/.

Especially for things like #36, a visual confirmation would help a lot to verify unit test expectations.

**Comment by YairRand** [comment]
Do you mean that there should be an area of the page that shows what the CSS in the box would look like, or that there should be a separate page with demo html?

**Comment by Krinkle** [comment]
As a separate page. One with HTML content and a stylesheet that applies various CSS properties to the layout and content. With a switch to toggle to an RTL version. Basically an example of how to use CSSJanus, and what it can do. This would function as a visual test suite of sorts to better understand the impact of when properties are and aren't flipped, and if so, how they are flipped, etc.

**Comment by YairRand** [comment]
Something roughly like [this](https://github.com/YairRand/cssjanus.github.io/blob/master/demopage.html)? (Just an example, not actually filled in or nice looking.) Or were you thinking more of a code-style-ish list of boxes with visual tests in them? Or something else?

**Comment by Krinkle** [comment]
@YairRand Yeah, something like that. Ideally with some self-documented paragraphs along the way as well. It's okay for it to be a long page that focusses on different aspects as different points (as opposed to all at once).

**Comment by YairRand** [comment]
Does [this](https://github.com/cssjanus/cssjanus.github.io/pull/2) fit the requirements? Maybe I should add a little more on the more common css properties? Or try to fiddle with the text blocks to help with the bidi issues?

**Comment by Krinkle** [comment]
@YairRand I've landed it in its current form since it's a great start.

A few minor changes:
* Set sans-serif font.
* Moved to `/demo/`.
* Changed to only swap ltr/rtl (since #36 is not yet merged).
* Added "Demo" link on home page.
