### ISSUE TITLE
Any way to deal with negative `text-indent`?

### ISSUE THREAD

**Issue by Volker-E** [cssjanus/cssjanus#58]
Over many years a `text-indent: -9999em` or similar was a common solution for image widgets, where the text was only meant to be visible to screenreaders. 
See for example: https://codepen.io/anon/pen/aqQWQJ

In RTL languages such property/value combinations could lead to unintended visibility of text.
It might be though to identify a clear path on when to switch it over.

**Comment by YairRand** [comment]
Assuming the page is also RTL, there should be no problem. `text-index` is relative to the text direction, not absolute, so the setting it to negative moves the text to the right in RTL, which is also where the scroll-start is, thus having the same effect as using the same CSS for LTR. The text would not be visible.

**Comment by Krinkle** [comment]
Closing as it seems to be resolved, but ping or re-open if you find otherwise.
