### ISSUE TITLE
How to use this package with "create-react-app"

### ISSUE THREAD

**Issue by Shaker-Hamdi** [cssjanus/cssjanus#71]
I'm using create-react-app and I'm taking the easy approach to flip the whole CSS file to RTL and load it based on a change in the state.

Changing the CSS file based on a prop in the state if the easy part, but I also want to convert the CSS file to RTL before that step, how to do that with this package?

**Comment by Krinkle** [comment]
The method for performing a flip of any CSS text is the same regardless of where it is inside your application. See also <https://github.com/cssjanus/cssjanus#basic-usage>

```js
flipped = cssjanus.transform( ltrInput );
```

If you're looking for which event handler to use within React, you will need to ask the React community instead. I'm afraid I don't know that off-hand. :-)
