### ISSUE TITLE
Flip transform: scaleX(-1)

### ISSUE THREAD

**Issue by danielhusar** [cssjanus/cssjanus#78]
Hey!

Thanks for this amazing library.

One suggestion:

Should `scaleX(1)` be flipped to `scaleX(-1)` and vice versa?

My use-case is the arrow icon, that points to the left, but in RTL it's on the other side, and the direction of arrow doesn't make sense any more.

**Comment by Krinkle** [comment]
Hi! This has been requested before at https://github.com/cssjanus/cssjanus/issues/47, which you may want to check out first.

My thinking is that CSSJanus is meant to work out-of-the-box for most cases without having to think about RTL. Based on that, it seems unlikely that developers would have `transform: scaleX(1);` set in their stylesheet as it would not do anything. Such code tends to be confusing in my opinion, and might get removed by your future self or someone else when it seems redundant.

For this use case, my previous recommendation was that either 1: Other properties are flipped making it work naturally (see the border/arrow trick shown at https://github.com/cssjanus/cssjanus/issues/47). Or 2: Something needs an explicit transformation for RTL, which might be easier to maintain/understand by setting explicitly with an RTL-specific `scaleX(-1)` rule.

Let me know if this works for you. I'm willing to reconsider this based on your experience!

**Comment by danielhusar** [comment]
Sorry for getting back this late!
All this makes sense, thanks!

I solved my issue by custom css for RTL that flips those. (As I have only few rules like that)
