### ISSUE TITLE
The demo is broken

### ISSUE THREAD

**Issue by lens0021** [cssjanus/cssjanus#83]
Visit https://cssjanus.github.io/demo/.

Console output:

> Uncaught TypeError: cssjanus.transform is not a function at HTMLButtonElement.buttons.<computed>.onclick ([(index):488](https://github.com/cssjanus/cssjanus/blob/b05caf9167ff14e626a737bd9869e6f07fae45e7/site/demo/index.html#L488))

**Comment by Krinkle** [comment]
This was (supposed to be) fixed by https://github.com/cssjanus/cssjanus/commit/569d68a00, and pulled through to the live site with https://github.com/cssjanus/cssjanus.github.io/commit/fc4c49370e8b57ad3bfd5d7b8094eb49b2ea5a3a.
