### ISSUE TITLE
/* @noflip */ doesn't work.

### ISSUE THREAD

**Issue by tamir61** [cssjanus/cssjanus#84]
Hi, I'm using  stylis-plugin-rtl plugin with StyleSheetManager and i'm trying to exclude some rule but it doesn't work

```
/* @noflip */
.stx_yaxis {
  /* y-axis price styles */
  font-size: 12px;
  font-family: Helvetica, sans-serif;
  color: #333;
  background-color: #003eb9;
  direction: ltr !important;
}
```

am I missing something?

**Comment by Krinkle** [comment]
Seems to work fine in the [**Demo**](https://cssjanus.github.io/#input/.stx_yaxis%20%7B%0A%20%20%2F*%20y-axis%20price%20styles%20*%2F%0A%20%20direction%3A%20ltr%20!important%3B%0A%7D%0A%0A%2F*%20%40noflip%20*%2F%0A.stx_yaxis%20%7B%0A%20%20%2F*%20y-axis%20price%20styles%20*%2F%0A%20%20direction%3A%20ltr%20!important%3B%0A%7D%0A%0A%0A).

Perhaps its an issue with how Stylis or [stylis-plugin-rtl](https://www.npmjs.com/package/stylis-plugin-rtl) works?

**Comment by Krinkle** [comment]
Hi @tamir61!

I've added your code to the [**Demo**](https://cssjanus.github.io/#input/.stx_yaxis%20%7B%0A%20%20%2F*%20y-axis%20price%20styles%20*%2F%0A%20%20direction%3A%20ltr%20!important%3B%0A%7D%0A%0A%2F*%20%40noflip%20*%2F%0A.stx_yaxis%20%7B%0A%20%20%2F*%20y-axis%20price%20styles%20*%2F%0A%20%20direction%3A%20ltr%20!important%3B%0A%7D%0A%0A%0A), and it appears to work fine.

Does it work when this code is the only content of your stylesheet? Or does it also happen then?

If it happens then as well, then I'm afraid this might be an issue with how Stylis or [stylis-plugin-rtl](https://www.npmjs.com/package/stylis-plugin-rtl) works internally. You may need to bring it to them to investigate. If they in turn find a deeper issue in CSSJanus with more information, I'd be happy to help resolve that. Feel free to mention/CC me in that issue if you report it there.

**Comment by andreisergiu98** [comment]
The reason it is not working with styled-components is because babel removes all comments when minifying, you can disable minification, but i wouldn't do that, or you can add an exclamation mark to instruct it to keep it, like this: `/*! @noflip */`. It's working fine for me so far.

**Comment by tamir61** [comment]
Hey, thanks for the comment. that was closed a few weeks ago. 
it actually does work. I missed something in my code
