### ISSUE TITLE
Tilde (~) subsequent-sibling combinator causes 'left' in class names to switch to 'right'

### ISSUE THREAD

**Issue by CaitlinSmart** [cssjanus/cssjanus#90]
When adding a tilde `~` after a class with the word 'left' in it, such as `first-sibling.left-class ~ second-sibling`, the word 'left' in the class name changes to 'right'.

[Example of tilde causing class name change.](https://cssjanus.github.io/#input/first-sibling.left-class%20%7B%0A%20%20margin-left%3A%20100px%3B%0A%7D%0A%0Afirst-sibling.left-class%20%2B%20second-sibling%20%7B%0A%20%20margin-left%3A%20100px%3B%0A%7D%0A%0Afirst-sibling.left-class%20~%20second-sibling%20%7B%0A%20%20margin-left%3A%20100px%3B%0A%7D)

**Comment by CaitlinSmart** [comment]
Just realized I'm using a (very) old version and this should be fixed in the latest version. Thanks!

**Comment by Krinkle** [comment]
@CaitlinSmart The demo on the website was also using an outdated version as well. I've fixed that now over at https://github.com/cssjanus/cssjanus.github.io.
