### ISSUE TITLE
License has generic copyright

### ISSUE THREAD

**Issue by CaitlinSmart** [cssjanus/cssjanus#91]
I'm updating CSSJanus in our codebase to the newest version (thank you!) and noticed the LICENSE.txt file has a generic copyright text 'Copyright [yyyy] [name of copyright owner]'.

Is this intentional? We want to make sure we are respecting the copyright.

**Comment by Krinkle** [comment]
Hi @CaitlinSmart,

I believe you're referring to the non-nominal section at the end of the LICENSE.txt file. This appendix is commonly distributed along with the Apache license as an instruction to authors (i.e. us) on how to apply the license, with a template for how to write the copyright notice. It is my understanding that this template is not the copyright notice itself and we generally do not to modify this kind of file to ease legal review and avoid delays.

In accordance with the instrutions, though, we have a header in major source files, with our actual copyright notice. There is also a NOTICE.txt file, in accordance with section 4d, in which the same copyright notice resides for easy reference with our names filled in.

Thanks for using CSSJanus! ♥️

**Comment by CaitlinSmart** [comment]
I see! Thank you for letting me know, I was unfamiliar with the Apache license.
